services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: story_app
      MYSQL_ROOT_PASSWORD: PanCake!
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
