services:
  backend:
    build: 
      context: ./backend
    command: >
      sh -c "mvn spring-boot:run"
    volumes:
      - ./backend:/backend
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: story_app
      MYSQL_ROOT_PASSWORD: PanCake!
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: