services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    command: >
      sh -c "npm run ng serve -- --host 0.0.0.0"
    volumes:
      - ./frontend/src:/frontend/src
  backend:
    build: 
      context: ./backend
    command: >
      sh -c "mvn spring-boot:run"
    volumes:
      - ./backend/src:/app/src
      - ./backend/pom.xml:/app/pom.xml
    environment:
      - SPRING_PROFILE_ACTIVE=dev
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:8.3
    environment:
      MYSQL_DATABASE: story_app
      MYSQL_ROOT_PASSWORD: PanCake!
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: