name: Spring Boot CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Navigate to backend directory
      run: cd backend

    - name: Build with Maven
      run: mvn -B clean package
